import pg from 'pg';

const db = new pg.Client({
    user: "postgres",
    host: "localhost",
    database: "book-notes",
    password: "123456",
    port: 5432,
});
db.connect();

async function dbQuery (query) {
    try {
        await db.query(query);
        console.log('Table checked (created if not exists).');
    } catch (err) {
        console.error('Error ensuring table exists:', err);
    }
}


const booksQuery = `
  INSERT INTO books (id, booktitle, summary, dateread, rating, author) VALUES 
  (5, '1984', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget commodo risus, at imperdiet lacus. Proin nec velit urna. Etiam aliquam convallis elit, et tristique odio convallis a. Pellentesque tortor sem, egestas eu nunc aliquam, pretium hendrerit sapien. Suspendisse potenti. Etiam egestas tincidunt neque, et facilisis nulla viverra facilisis. Mauris in sem ut elit commodo mattis. Nunc commodo enim nec ullamcorper dictum. Cras a velit magna. Suspendisse ut tristique erat, nec sodales lacus. Mauris facilisis dictum eros, at aliquam velit mattis nec. Etiam gravida facilisis turpis, eu viverra tellus rhoncus ac. Mauris convallis dui massa, et suscipit magna cursus quis.
Vestibulum pretium ut massa vel luctus. Etiam accumsan, nisl nec pulvinar dictum, leo neque volutpat lectus, vitae pretium risus massa egestas lacus. Pellentesque at facilisis nulla. Pellentesque viverra turpis non risus feugiat pretium. Duis condimentum lorem a orci pretium, nec tincidunt nibh ultricies. Mauris interdum efficitur dictum. Phasellus lobortis mauris at neque convallis, sed tincidunt risus tincidunt. Sed ut tincidunt ex. Fusce turpis urna, varius sit amet porta vitae, euismod sit amet mauris.
Nullam at cursus magna. Proin vulputate massa enim, eu eleifend purus interdum nec. Mauris ac enim urna. Quisque accumsan, lectus eu maximus cursus, ipsum nulla dictum libero, vel tempus odio enim nec elit. Suspendisse eget pulvinar ipsum. Quisque cursus diam nisi, eu scelerisque velit varius sed. Etiam pharetra egestas lorem, sit amet accumsan ligula elementum at. Maecenas euismod odio id erat dictum, vitae rutrum erat euismod. Sed eget pretium tortor, in gravida urna.
Proin consectetur accumsan nibh, ac feugiat odio convallis ac. In hac habitasse platea dictumst. Nam vulputate dictum sapien, nec suscipit erat. Nam sodales, velit nec fermentum pretium, ex erat hendrerit nisi, id laoreet urna velit nec sapien. Nullam nec dolor id orci commodo euismod. Mauris volutpat ligula nec ante malesuada dapibus. Etiam elit mi, mattis ac efficitur sit amet, malesuada nec libero. Suspendisse potenti. Pellentesque aliquam nibh eu ante posuere, a dictum erat accumsan. Maecenas eget ex cursus, venenatis urna consectetur, dictum enim.
In semper vulputate nisi, ac rhoncus velit laoreet in. Etiam volutpat sed sapien ut dictum. Etiam nec urna eu lectus sodales laoreet. Integer hendrerit placerat tristique. Pellentesque sit amet sollicitudin ante, vel hendrerit lacus. Sed eget urna nec magna suscipit dictum eu nec ex. Pellentesque ornare, enim at aliquam placerat, nisl libero pretium turpis, vel ultrices ex ante at enim. Nulla vel pulvinar urna, eu scelerisque metus. Vestibulum id enim vel nisi rutrum scelerisque sit amet vel risus. Duis euismod, risus sed hendrerit consectetur, massa orci auctor sem, eu lacinia leo sem sit amet erat. Etiam elit magna, dictum nec cursus ac, dictum non odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam egestas commodo magna, id consequat tortor auctor at. Aliquam erat volutpat.
', '2025-06-03', 5, 'George Orwell'),
  (7, 'Great Expectations', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget commodo risus, at imperdiet lacus. Proin nec velit urna. Etiam aliquam convallis elit, et tristique odio convallis a. Pellentesque tortor sem, egestas eu nunc aliquam, pretium hendrerit sapien. Suspendisse potenti. Etiam egestas tincidunt neque, et facilisis nulla viverra facilisis. Mauris in sem ut elit commodo mattis. Nunc commodo enim nec ullamcorper dictum. Cras a velit magna. Suspendisse ut tristique erat, nec sodales lacus. Mauris facilisis dictum eros, at aliquam velit mattis nec. Etiam gravida facilisis turpis, eu viverra tellus rhoncus ac. Mauris convallis dui massa, et suscipit magna cursus quis.
Vestibulum pretium ut massa vel luctus. Etiam accumsan, nisl nec pulvinar dictum, leo neque volutpat lectus, vitae pretium risus massa egestas lacus. Pellentesque at facilisis nulla. Pellentesque viverra turpis non risus feugiat pretium. Duis condimentum lorem a orci pretium, nec tincidunt nibh ultricies. Mauris interdum efficitur dictum. Phasellus lobortis mauris at neque convallis, sed tincidunt risus tincidunt. Sed ut tincidunt ex. Fusce turpis urna, varius sit amet porta vitae, euismod sit amet mauris.
Nullam at cursus magna. Proin vulputate massa enim, eu eleifend purus interdum nec. Mauris ac enim urna. Quisque accumsan, lectus eu maximus cursus, ipsum nulla dictum libero, vel tempus odio enim nec elit. Suspendisse eget pulvinar ipsum. Quisque cursus diam nisi, eu scelerisque velit varius sed. Etiam pharetra egestas lorem, sit amet accumsan ligula elementum at. Maecenas euismod odio id erat dictum, vitae rutrum erat euismod. Sed eget pretium tortor, in gravida urna.
Proin consectetur accumsan nibh, ac feugiat odio convallis ac. In hac habitasse platea dictumst. Nam vulputate dictum sapien, nec suscipit erat. Nam sodales, velit nec fermentum pretium, ex erat hendrerit nisi, id laoreet urna velit nec sapien. Nullam nec dolor id orci commodo euismod. Mauris volutpat ligula nec ante malesuada dapibus. Etiam elit mi, mattis ac efficitur sit amet, malesuada nec libero. Suspendisse potenti. Pellentesque aliquam nibh eu ante posuere, a dictum erat accumsan. Maecenas eget ex cursus, venenatis urna consectetur, dictum enim.
In semper vulputate nisi, ac rhoncus velit laoreet in. Etiam volutpat sed sapien ut dictum. Etiam nec urna eu lectus sodales laoreet. Integer hendrerit placerat tristique. Pellentesque sit amet sollicitudin ante, vel hendrerit lacus. Sed eget urna nec magna suscipit dictum eu nec ex. Pellentesque ornare, enim at aliquam placerat, nisl libero pretium turpis, vel ultrices ex ante at enim. Nulla vel pulvinar urna, eu scelerisque metus. Vestibulum id enim vel nisi rutrum scelerisque sit amet vel risus. Duis euismod, risus sed hendrerit consectetur, massa orci auctor sem, eu lacinia leo sem sit amet erat. Etiam elit magna, dictum nec cursus ac, dictum non odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam egestas commodo magna, id consequat tortor auctor at. Aliquam erat volutpat.
', '2025-06-19', 7, 'Charles Dickens'),
  (4, 'To Kill a Mockingbird', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget commodo risus, at imperdiet lacus. Proin nec velit urna. Etiam aliquam convallis elit, et tristique odio convallis a. Pellentesque tortor sem, egestas eu nunc aliquam, pretium hendrerit sapien. Suspendisse potenti. Etiam egestas tincidunt neque, et facilisis nulla viverra facilisis. Mauris in sem ut elit commodo mattis. Nunc commodo enim nec ullamcorper dictum. Cras a velit magna. Suspendisse ut tristique erat, nec sodales lacus. Mauris facilisis dictum eros, at aliquam velit mattis nec. Etiam gravida facilisis turpis, eu viverra tellus rhoncus ac. Mauris convallis dui massa, et suscipit magna cursus quis.
Vestibulum pretium ut massa vel luctus. Etiam accumsan, nisl nec pulvinar dictum, leo neque volutpat lectus, vitae pretium risus massa egestas lacus. Pellentesque at facilisis nulla. Pellentesque viverra turpis non risus feugiat pretium. Duis condimentum lorem a orci pretium, nec tincidunt nibh ultricies. Mauris interdum efficitur dictum. Phasellus lobortis mauris at neque convallis, sed tincidunt risus tincidunt. Sed ut tincidunt ex. Fusce turpis urna, varius sit amet porta vitae, euismod sit amet mauris.
Nullam at cursus magna. Proin vulputate massa enim, eu eleifend purus interdum nec. Mauris ac enim urna. Quisque accumsan, lectus eu maximus cursus, ipsum nulla dictum libero, vel tempus odio enim nec elit. Suspendisse eget pulvinar ipsum. Quisque cursus diam nisi, eu scelerisque velit varius sed. Etiam pharetra egestas lorem, sit amet accumsan ligula elementum at. Maecenas euismod odio id erat dictum, vitae rutrum erat euismod. Sed eget pretium tortor, in gravida urna.
Proin consectetur accumsan nibh, ac feugiat odio convallis ac. In hac habitasse platea dictumst. Nam vulputate dictum sapien, nec suscipit erat. Nam sodales, velit nec fermentum pretium, ex erat hendrerit nisi, id laoreet urna velit nec sapien. Nullam nec dolor id orci commodo euismod. Mauris volutpat ligula nec ante malesuada dapibus. Etiam elit mi, mattis ac efficitur sit amet, malesuada nec libero. Suspendisse potenti. Pellentesque aliquam nibh eu ante posuere, a dictum erat accumsan. Maecenas eget ex cursus, venenatis urna consectetur, dictum enim.
In semper vulputate nisi, ac rhoncus velit laoreet in. Etiam volutpat sed sapien ut dictum. Etiam nec urna eu lectus sodales laoreet. Integer hendrerit placerat tristique. Pellentesque sit amet sollicitudin ante, vel hendrerit lacus. Sed eget urna nec magna suscipit dictum eu nec ex. Pellentesque ornare, enim at aliquam placerat, nisl libero pretium turpis, vel ultrices ex ante at enim. Nulla vel pulvinar urna, eu scelerisque metus. Vestibulum id enim vel nisi rutrum scelerisque sit amet vel risus. Duis euismod, risus sed hendrerit consectetur, massa orci auctor sem, eu lacinia leo sem sit amet erat. Etiam elit magna, dictum nec cursus ac, dictum non odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam egestas commodo magna, id consequat tortor auctor at. Aliquam erat volutpat.
', '2025-06-25', 4, 'Harper Lee'),
  (3, 'The Great Gatsby', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget commodo risus, at imperdiet lacus. Proin nec velit urna. Etiam aliquam convallis elit, et tristique odio convallis a. Pellentesque tortor sem, egestas eu nunc aliquam, pretium hendrerit sapien. Suspendisse potenti. Etiam egestas tincidunt neque, et facilisis nulla viverra facilisis. Mauris in sem ut elit commodo mattis. Nunc commodo enim nec ullamcorper dictum. Cras a velit magna. Suspendisse ut tristique erat, nec sodales lacus. Mauris facilisis dictum eros, at aliquam velit mattis nec. Etiam gravida facilisis turpis, eu viverra tellus rhoncus ac. Mauris convallis dui massa, et suscipit magna cursus quis.
Vestibulum pretium ut massa vel luctus. Etiam accumsan, nisl nec pulvinar dictum, leo neque volutpat lectus, vitae pretium risus massa egestas lacus. Pellentesque at facilisis nulla. Pellentesque viverra turpis non risus feugiat pretium. Duis condimentum lorem a orci pretium, nec tincidunt nibh ultricies. Mauris interdum efficitur dictum. Phasellus lobortis mauris at neque convallis, sed tincidunt risus tincidunt. Sed ut tincidunt ex. Fusce turpis urna, varius sit amet porta vitae, euismod sit amet mauris.
Nullam at cursus magna. Proin vulputate massa enim, eu eleifend purus interdum nec. Mauris ac enim urna. Quisque accumsan, lectus eu maximus cursus, ipsum nulla dictum libero, vel tempus odio enim nec elit. Suspendisse eget pulvinar ipsum. Quisque cursus diam nisi, eu scelerisque velit varius sed. Etiam pharetra egestas lorem, sit amet accumsan ligula elementum at. Maecenas euismod odio id erat dictum, vitae rutrum erat euismod. Sed eget pretium tortor, in gravida urna.
Proin consectetur accumsan nibh, ac feugiat odio convallis ac. In hac habitasse platea dictumst. Nam vulputate dictum sapien, nec suscipit erat. Nam sodales, velit nec fermentum pretium, ex erat hendrerit nisi, id laoreet urna velit nec sapien. Nullam nec dolor id orci commodo euismod. Mauris volutpat ligula nec ante malesuada dapibus. Etiam elit mi, mattis ac efficitur sit amet, malesuada nec libero. Suspendisse potenti. Pellentesque aliquam nibh eu ante posuere, a dictum erat accumsan. Maecenas eget ex cursus, venenatis urna consectetur, dictum enim.
In semper vulputate nisi, ac rhoncus velit laoreet in. Etiam volutpat sed sapien ut dictum. Etiam nec urna eu lectus sodales laoreet. Integer hendrerit placerat tristique. Pellentesque sit amet sollicitudin ante, vel hendrerit lacus. Sed eget urna nec magna suscipit dictum eu nec ex. Pellentesque ornare, enim at aliquam placerat, nisl libero pretium turpis, vel ultrices ex ante at enim. Nulla vel pulvinar urna, eu scelerisque metus. Vestibulum id enim vel nisi rutrum scelerisque sit amet vel risus. Duis euismod, risus sed hendrerit consectetur, massa orci auctor sem, eu lacinia leo sem sit amet erat. Etiam elit magna, dictum nec cursus ac, dictum non odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam egestas commodo magna, id consequat tortor auctor at. Aliquam erat volutpat.
', '2025-06-02', 1, 'F. Scott Fitzgerald'),
  (6, 'The Catcher in the Rye', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget commodo risus, at imperdiet lacus. Proin nec velit urna. Etiam aliquam convallis elit, et tristique odio convallis a. Pellentesque tortor sem, egestas eu nunc aliquam, pretium hendrerit sapien. Suspendisse potenti. Etiam egestas tincidunt neque, et facilisis nulla viverra facilisis. Mauris in sem ut elit commodo mattis. Nunc commodo enim nec ullamcorper dictum. Cras a velit magna. Suspendisse ut tristique erat, nec sodales lacus. Mauris facilisis dictum eros, at aliquam velit mattis nec. Etiam gravida facilisis turpis, eu viverra tellus rhoncus ac. Mauris convallis dui massa, et suscipit magna cursus quis.
Vestibulum pretium ut massa vel luctus. Etiam accumsan, nisl nec pulvinar dictum, leo neque volutpat lectus, vitae pretium risus massa egestas lacus. Pellentesque at facilisis nulla. Pellentesque viverra turpis non risus feugiat pretium. Duis condimentum lorem a orci pretium, nec tincidunt nibh ultricies. Mauris interdum efficitur dictum. Phasellus lobortis mauris at neque convallis, sed tincidunt risus tincidunt. Sed ut tincidunt ex. Fusce turpis urna, varius sit amet porta vitae, euismod sit amet mauris.
Nullam at cursus magna. Proin vulputate massa enim, eu eleifend purus interdum nec. Mauris ac enim urna. Quisque accumsan, lectus eu maximus cursus, ipsum nulla dictum libero, vel tempus odio enim nec elit. Suspendisse eget pulvinar ipsum. Quisque cursus diam nisi, eu scelerisque velit varius sed. Etiam pharetra egestas lorem, sit amet accumsan ligula elementum at. Maecenas euismod odio id erat dictum, vitae rutrum erat euismod. Sed eget pretium tortor, in gravida urna.
Proin consectetur accumsan nibh, ac feugiat odio convallis ac. In hac habitasse platea dictumst. Nam vulputate dictum sapien, nec suscipit erat. Nam sodales, velit nec fermentum pretium, ex erat hendrerit nisi, id laoreet urna velit nec sapien. Nullam nec dolor id orci commodo euismod. Mauris volutpat ligula nec ante malesuada dapibus. Etiam elit mi, mattis ac efficitur sit amet, malesuada nec libero. Suspendisse potenti. Pellentesque aliquam nibh eu ante posuere, a dictum erat accumsan. Maecenas eget ex cursus, venenatis urna consectetur, dictum enim.
In semper vulputate nisi, ac rhoncus velit laoreet in. Etiam volutpat sed sapien ut dictum. Etiam nec urna eu lectus sodales laoreet. Integer hendrerit placerat tristique. Pellentesque sit amet sollicitudin ante, vel hendrerit lacus. Sed eget urna nec magna suscipit dictum eu nec ex. Pellentesque ornare, enim at aliquam placerat, nisl libero pretium turpis, vel ultrices ex ante at enim. Nulla vel pulvinar urna, eu scelerisque metus. Vestibulum id enim vel nisi rutrum scelerisque sit amet vel risus. Duis euismod, risus sed hendrerit consectetur, massa orci auctor sem, eu lacinia leo sem sit amet erat. Etiam elit magna, dictum nec cursus ac, dictum non odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam egestas commodo magna, id consequat tortor auctor at. Aliquam erat volutpat.
', '2025-06-05', 8, 'J. D. Salinger')
`;

dbQuery(booksQuery);

const notesQuery = `
  INSERT INTO notes (id, content, bookid) VALUES 
  (22, 'Lorem ipsum dolor sit amet', 3),
  (23, 'Lorem ipsum dolor sit amet', 3), 
  (24, 'Lorem ipsum dolor sit amet', 3),
  (25, 'Lorem ipsum dolor sit amet', 4),
  (26, 'Lorem ipsum dolor sit amet', 4),
  (27, 'Lorem ipsum dolor sit amet', 4),
  (28, 'Lorem ipsum dolor sit amet', 5),
  (29, 'Lorem ipsum dolor sit amet', 5),
  (30, 'Lorem ipsum dolor sit amet', 5),
  (31, 'Lorem ipsum dolor sit amet', 6),
  (32, 'Lorem ipsum dolor sit amet', 6),
  (33, 'Lorem ipsum dolor sit amet', 6),
  (34, 'Lorem ipsum dolor sit amet', 7),
  (35, 'Lorem ipsum dolor sit amet', 7),
  (36, 'Lorem ipsum dolor sit amet', 7)
`;


// await dbQuery(booksQuery);
await dbQuery(notesQuery);

db.close();
